// index.js
var path = require('path');
module.exports = {
	rootPath:path.join(__dirname,"../"),
	defaultJSON:{
	"comment":"这里是注释",
	"activeDes":"活动说明：通过本次活动报名参加的用户，可享受我爱我家与开发商联合的购房优惠，具体优惠即可购房源以开发商售楼处公示为准。",
	"city":"成都",
	"reqUrl":"https://ecapi.maifangbar.com/v1/page/activity_registration",
	"products":[
		{
			"name":"项目名称1",
			"subTitle":"副标题1",
			"area":"区域1",
			"keys":"亮点描述1",
			"price":"价格描述1",
			"saleoff":35,
			"link":"http://www.baidu.com",
			"id":"1",
			"imgUrl":"img/pic_house.png",
			"phone_1":"1234",
			"phone_2":"2234",
			"type":1
		},
		{
			"name":"项目名称2",
			"subTitle":"副标题1",
			"area":"区域2",
			"keys":"亮点描述2",
			"price":"价格描述2",
			"saleoff":0,
			"link":"http://www.google.com",
			"id":"2",
			"imgUrl":"img/pic_house.png",
			"phone_1":"1234",
			"phone_2":"2234",
			"type":0
		},
		{
			"name":"项目名称3",
			"subTitle":"副标题1",
			"area":"区域2",
			"keys":"亮点描述3",
			"price":"价格描述3",
			"saleoff":50,
			"link":"http://www.liujians.me",
			"id":"3",
			"imgUrl":"img/pic_house.png",
			"phone_1":"1234",
			"phone_2":"2234",
			"type":1
		}
	]
}
}